### ISSUE TITLE
I have this problem

### ISSUE THREAD

**Issue by Sachin85y** [sarperavci/MXS#9]
[i] Timeout: 15 seconds
Traceback (most recent call last):jectable URLs
  File "/root/MXS/MXS.py", line 21, in <module>
    scanner.run()
  File "/root/MXS/func.py", line 121, in run
    asyncio.run(self.scan())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/MXS/func.py", line 99, in scan
    async with aiohttp.ClientSession(timeout=timeout, connector=aiohttp.TCPConnector(ssl=False, limit=0, enable_cleanup_closed=True)) as session:
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1140, in __aexit__
    await self.close()
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1006, in close
    await self._connector.close()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 792, in close
    return super().close()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 409, in close
    self._close()
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 439, in _close
    transport.abort()
  File "/usr/lib/python3.11/asyncio/sslproto.py", line 247, in abort
    self._ssl_protocol._abort()
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_abort'

**Comment by M-Enes** [comment]
Please give us more information about your situation. Could you show what parameters did you pass to mxs.py?
You should also check version of **aiohttp** and **asyncio** which is dependencies for the MXS.

**Comment by M-Enes** [comment]
It seems you are using an old version of asyncio. Please update the package.
